apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  params:
  - name: GitHubOrg
    value: "pranathi0608"
  - name: GitHubUser
    value: "pranathi0608"
  - name: GitHubRepo
    value: "https://github.com/Pranathi0608/triggers.git"
  - name: GitHubSecretName
    value: webhook-secret
  - name: GitHubAccessTokenKey
    value: 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
  - name: GitHubSecretStringKey
    value: secret
    name: ExternalDomain
    value: getting-started.iancoffey.com
#   If you are using github enterprise, provide a value for GitHubDomain
#  - name: GitHubDomain
#    value: git.corp.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
